version: '3.9'

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - ~/.PG/PG_DATA:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000


