# Generated by Django 4.2.1 on 2023-05-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cargos',
                                   to='cargo.location')),
                ('pick_up',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_cargos',
                                   to='cargo.location')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('capacity', models.IntegerField()),
                ('current_location',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.location')),
            ],
        ),
    ]
